spring:
  application:
    name: music-store
  data:
    mongodb:
      uri: mongodb://mila:mila@localhost:27017/music-store-db?authSource=admin&retryWrites=true
      connection-timeout: 30000
      socket-timeout: 30000
      retry-writes: true
      max-wait-time: 60000
  retry:
    max-attmepts: 5
    delay: 2