spring:
  application:
    name: music-store
  data:
    mongodb:
      uri: mongodb://mila:mila@localhost:27017/music-store-db?authSource=admin
      port: 27017
      database: music-store-db
  retry:
    max-attempts: 5
    delay: 2s