name: Build Music Store App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build Music Store Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '19'

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: | 
          mvn clean
          mvn -B package --file pom.xml